### ISSUE TITLE
Create CourseBanner component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#10]
![image](https://github.com/Duran-Enterprise/deep/assets/128191960/969f964f-2249-4ef2-8eab-c60f199a820a)

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="styleguide.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="the-deep-project">
            <div class="header">The D.E.E.P. Project</div>
            <p class="text-wrapper">
                D.E.E.P. stands for Dedication, Empowerment, Education, and Programming — the foundation of our mission to
                provide accessible, project-based learning for all aspiring programmers.
            </p>
            <div class="course-cards">
                <div class="div">
                    <div class="card">
                        <div class="card-2">
                            <img class="building-block" src="img/building-block-svgrepo-com.svg" />
                            <div class="text-wrapper-2">Modularized</div>
                        </div>
                    </div>
                    <p class="text-wrapper-3">Learn in modules for flexibility.</p>
                </div>
                <div class="div">
                    <div class="card">
                        <div class="card-3">
                            <img class="building" src="img/building-construction-svgrepo-com.svg" />
                            <div class="text-wrapper-2">Project-based</div>
                        </div>
                    </div>
                    <div class="text-wrapper-3">Hands-on coding with projects.</div>
                </div>
                <div class="div">
                    <div class="card">
                        <div class="card-3">
                            <img class="layer" src="img/layer-2.png" />
                            <div class="text-wrapper-2">Industry-relevant</div>
                        </div>
                    </div>
                    <div class="text-wrapper-3">Skills for tech careers.</div>
                </div>
            </div>
        </div>
    </body>
</html>
```
</details>

<details>
<summary>style.css</summary>

```css
.the-deep-project {
    display: inline-flex;
    flex-direction: column;
    max-width: 1080px;
    align-items: center;
    gap: 9px;
    padding: 0px 257px;
    position: relative;
}

.the-deep-project .header {
    position: relative;
    width: fit-content;
    margin-top: -1px;
    margin-left: -3px;
    margin-right: -3px;
    font-family: "Inter-BoldItalic", Helvetica;
    font-weight: 700;
    font-style: italic;
    color: #000000;
    font-size: 60px;
    letter-spacing: 0;
    line-height: 60px;
    white-space: nowrap;
}

.the-deep-project .text-wrapper {
    position: relative;
    align-self: stretch;
    font-family: "Inter-Light", Helvetica;
    font-weight: 300;
    color: #1f1f1f;
    font-size: 20px;
    text-align: center;
    letter-spacing: 0;
    line-height: 20px;
}

.the-deep-project .course-cards {
    display: inline-flex;
    align-items: flex-start;
    justify-content: center;
    gap: 29px;
    padding: 36px 0px 0px;
    position: relative;
    flex: 0 0 auto;
    margin-left: -76px;
    margin-right: -76px;
}

.the-deep-project .div {
    display: inline-flex;
    flex-direction: column;
    align-items: center;
    gap: 20px;
    position: relative;
    flex: 0 0 auto;
}

.the-deep-project .card {
    display: inline-flex;
    flex: 0 0 auto;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    position: relative;
}

.the-deep-project .card-2 {
    display: flex;
    width: 220px;
    height: 220px;
    gap: 10px;
    padding: 15px 24px 64px;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    overflow: hidden;
    border: 1px solid;
    border-color: #000000;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    position: relative;
}

.the-deep-project .building-block {
    position: relative;
    width: 74.07px;
    height: 80px;
}

.the-deep-project .text-wrapper-2 {
    position: relative;
    width: fit-content;
    font-family: "Inter-SemiBold", Helvetica;
    font-weight: 600;
    color: #00060a;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
}

.the-deep-project .text-wrapper-3 {
    position: relative;
    align-self: stretch;
    font-family: "Inter-Regular", Helvetica;
    font-weight: 400;
    color: #000000;
    font-size: 20px;
    text-align: center;
    letter-spacing: 0;
    line-height: 20px;
}

.the-deep-project .card-3 {
    display: flex;
    width: 220px;
    height: 220px;
    gap: 16px;
    padding: 15px 24px 64px;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    overflow: hidden;
    border: 1px solid;
    border-color: #000000;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    position: relative;
}

.the-deep-project .building {
    position: relative;
    width: 60px;
    height: 60px;
}

.the-deep-project .layer {
    position: relative;
    width: 46.01px;
    height: 56.84px;
}

```

</details>

<details>
<summary>styleguide.css</summary>

```css
:root {
    --white: rgba(234, 236, 246, 1);
    --black: rgba(0, 6, 10, 1);
    --accent: rgba(7, 157, 237, 1);
    --dark-contrast: rgba(34, 32, 32, 1);
    --buttonsprimary: rgba(22, 119, 172, 1);
    --buttonssecondary: rgba(196, 233, 253, 1);
    --variable-collection-light-contrast: rgba(220, 223, 240, 1);
}

```
</details>
