### ISSUE TITLE
Create CallToAction component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#11]
![image](https://github.com/Duran-Enterprise/deep/assets/128191960/827daa1f-d46c-4177-bfa7-8e31d2c87c17)

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="styleguide.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="main">
            <div class="course">
                <p class="header">
                    <span class="text-wrapper">Start your coding journey </span>
                    <span class="span">now</span>
                    <span class="text-wrapper">!</span>
                </p>
                <div class="navbar">
                    <div class="div">HTML</div>
                    <div class="div">❖</div>
                    <div class="div">CSS</div>
                    <div class="div">❖</div>
                    <div class="div">Javascript</div>
                    <div class="div">❖</div>
                    <div class="div">Python</div>
                </div>
            </div>
        </div>
    </body>
</html>

```
</details>

<details>
<summary>style.css</summary>

```css
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="styleguide.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="main">
            <div class="course">
                <p class="header">
                    <span class="text-wrapper">Start your coding journey </span>
                    <span class="span">now</span>
                    <span class="text-wrapper">!</span>
                </p>
                <div class="navbar">
                    <div class="div">HTML</div>
                    <div class="div">❖</div>
                    <div class="div">CSS</div>
                    <div class="div">❖</div>
                    <div class="div">Javascript</div>
                    <div class="div">❖</div>
                    <div class="div">Python</div>
                </div>
            </div>
        </div>
    </body>
</html>

```

</details>

<details>
<summary>styleguide.css</summary>

```css
:root {
    --white: rgba(234, 236, 246, 1);
    --black: rgba(0, 6, 10, 1);
    --accent: rgba(7, 157, 237, 1);
    --dark-contrast: rgba(34, 32, 32, 1);
    --buttonsprimary: rgba(22, 119, 172, 1);
    --buttonssecondary: rgba(196, 233, 253, 1);
    --variable-collection-light-contrast: rgba(220, 223, 240, 1);
}

```
</details>
