### ISSUE TITLE
Create Button component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#12]
![image](https://github.com/Duran-Enterprise/deep/assets/128191960/764cff6e-4b06-451b-82fa-6ff17fb74e4e)

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="styleguide.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="buttons">
            <button class="get-started"><button class="button">Get Started</button></button>
            <button class="learn-more"><button class="text-wrapper">Learn More</button></button>
        </div>
    </body>
</html>

```
</details>

<details>
<summary>style.css</summary>

```css
.buttons {
    display: inline-flex;
    align-items: center;
    gap: 18px;
    padding: 20px 0px;
    position: relative;
}

.buttons .get-started {
    display: flex;
    flex-direction: column;
    width: 199px;
    height: 48px;
    align-items: center;
    justify-content: center;
    gap: 10px;
    padding: 8px 24px;
    position: relative;
    background-color: #079ded;
    border-radius: 15px;
    overflow: hidden;
    all: unset;
    box-sizing: border-box;
}

.buttons .button {
    color: #ffffff;
    position: relative;
    width: fit-content;
    font-family: "Inter-Regular", Helvetica;
    font-weight: 400;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
    all: unset;
    box-sizing: border-box;
}

.buttons .learn-more {
    display: flex;
    flex-direction: column;
    width: 199px;
    height: 48px;
    align-items: center;
    justify-content: center;
    gap: 10px;
    padding: 8px 24px;
    position: relative;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    overflow: hidden;
    all: unset;
    box-sizing: border-box;
}

.buttons .text-wrapper {
    color: #00060a;
    position: relative;
    width: fit-content;
    font-family: "Inter-Regular", Helvetica;
    font-weight: 400;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
    all: unset;
    box-sizing: border-box;
}

```

</details>

<details>
<summary>styleguide.css</summary>

```css
:root {
    --white: rgba(234, 236, 246, 1);
    --black: rgba(0, 6, 10, 1);
    --accent: rgba(7, 157, 237, 1);
    --dark-contrast: rgba(34, 32, 32, 1);
    --buttonsprimary: rgba(22, 119, 172, 1);
    --buttonssecondary: rgba(196, 233, 253, 1);
    --variable-collection-light-contrast: rgba(220, 223, 240, 1);
}

```
</details>
