### ISSUE TITLE
Create Navbar component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#2]

**Comment by DDuran19** [comment]
![Image](https://github.com/Duran-Enterprise/deep/assets/128191960/c51cd0ba-2c00-41f9-a492-1f3cc81e2dfd)


<details>
<summary>styleguide.css</summary>

```css
    :root {
        --white: rgba(234, 236, 246, 1);
        --black: rgba(0, 6, 10, 1);
        --accent: rgba(7, 157, 237, 1);
        --dark-contrast: rgba(34, 32, 32, 1);
        --buttonsprimary: rgba(22, 119, 172, 1);
        --buttonssecondary: rgba(196, 233, 253, 1);
        --variable-collection-light-contrast: rgba(220, 223, 240, 1);
    }
```
</details>

<details>

<summary>style.css</summary>

```css
    .box {
        position: relative;
        width: 1119px;
        height: 188px;
    }
    
    .box .navbar {
        position: fixed;
        width: 1119px;
        height: 188px;
        top: 0;
        left: 0;
        border-radius: 5px;
        overflow: hidden;
        border: 1px dashed;
        border-color: #9747ff;
    }
    
    .box .mode-dark {
        display: inline-flex;
        max-width: 1080px;
        align-items: center;
        gap: 397px;
        padding: 6px 10px;
        position: absolute;
        top: 104px;
        left: 20px;
    }
    
    .box .branding {
        display: inline-flex;
        align-items: center;
        gap: 2px;
        padding: 1px 10px 1px 0px;
        position: relative;
        flex: 0 0 auto;
    }
    
    .box .img {
        position: relative;
        width: 32px;
        height: 32px;
    }
    
    .box .DEEP {
        position: relative;
        width: 151.8px;
        height: 37px;
        overflow: hidden;
    }
    
    .box .text-wrapper {
        position: absolute;
        width: 155px;
        height: 66px;
        top: 3px;
        left: -2px;
        text-shadow: -5px 6px 4px #1e1e1eb5;
        background: linear-gradient(180deg, rgb(7, 157, 237) 0%, rgb(0, 37.13, 61.89) 100%);
        -webkit-background-clip: text !important;
        background-clip: text;
        -webkit-text-fill-color: transparent;
        text-fill-color: transparent;
        font-family: "Bevan-Regular", Helvetica;
        font-weight: 400;
        color: transparent;
        font-size: 32px;
        letter-spacing: 0;
        line-height: 100px;
        white-space: nowrap;
    }
    
    .box .div {
        display: flex;
        width: 446px;
        align-items: center;
        justify-content: space-between;
        padding: 0px 10px;
        position: relative;
    }
    
    .box .text-wrapper-2 {
        position: relative;
        width: fit-content;
        margin-top: -1px;
        font-family: "Bevan-Regular", Helvetica;
        font-weight: 400;
        color: #f5fbff;
        font-size: 16px;
        text-align: center;
        letter-spacing: 0;
        line-height: 50px;
        white-space: nowrap;
    }
    
    .box .mode-light {
        display: inline-flex;
        max-width: 1080px;
        align-items: center;
        gap: 397px;
        padding: 6px 10px;
        position: absolute;
        top: 20px;
        left: 20px;
    }
    
    .box .text-wrapper-3 {
        position: relative;
        width: fit-content;
        margin-top: -1px;
        font-family: "Bevan-Regular", Helvetica;
        font-weight: 400;
        color: #090b15;
        font-size: 16px;
        text-align: center;
        letter-spacing: 0;
        line-height: 50px;
        white-space: nowrap;
    }
```

</details>

<details>
<summary>index.html</summary>

```html
    <!DOCTYPE html>
    <html>
        <head>
            <link rel="stylesheet" href="globals.css" />
            <link rel="stylesheet" href="styleguide.css" />
            <link rel="stylesheet" href="style.css" />
        </head>
        <body>
            <div class="box">
                <div class="navbar">
                    <div class="mode-dark">
                        <div class="branding">
                            <img class="img" src="img/size-11-2.svg" />
                            <div class="DEEP"><div class="text-wrapper">DEEP</div></div>
                        </div>
                        <div class="div">
                            <img class="img" src="img/dark-mode-toggle.svg" />
                            <div class="text-wrapper-2">Home</div>
                            <div class="text-wrapper-2">Courses</div>
                            <div class="text-wrapper-2">Projects</div>
                            <div class="text-wrapper-2">Login</div>
                        </div>
                    </div>
                    <div class="mode-light">
                        <div class="branding">
                            <img class="img" src="img/size-11.svg" />
                            <div class="DEEP"><div class="text-wrapper">DEEP</div></div>
                        </div>
                        <div class="div">
                            <img class="img" src="img/image.svg" />
                            <div class="text-wrapper-3">Home</div>
                            <div class="text-wrapper-3">Courses</div>
                            <div class="text-wrapper-3">Projects</div>
                            <div class="text-wrapper-3">Login</div>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </html>
```
</details>
