### ISSUE TITLE
Create Footer Component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#3]
![Image](https://github.com/Duran-Enterprise/deep/assets/128191960/f00df9fc-6f93-49fb-9805-5bc6d8311b9c)

<details>
<summary>styleguide.css</summary>

```css
    :root {
        --white: rgba(234, 236, 246, 1);
        --black: rgba(0, 6, 10, 1);
        --accent: rgba(7, 157, 237, 1);
        --dark-contrast: rgba(34, 32, 32, 1);
        --buttonsprimary: rgba(22, 119, 172, 1);
        --buttonssecondary: rgba(196, 233, 253, 1);
        --variable-collection-light-contrast: rgba(220, 223, 240, 1);
    }

```
</details>

<details>

<summary>style.css</summary>

```css
    .box {
        position: relative;
        width: 1088px;
        height: 442px;
    }

    .box .footer {
        position: fixed;
        width: 1088px;
        height: 442px;
        top: 0;
        left: 0;
        background-color: transparent;
        border-radius: 5px;
        overflow: hidden;
        border: 1px dashed;
        border-color: #9747ff;
    }

    .box .mode-light {
        display: flex;
        width: 1048px;
        min-height: 200px;
        max-height: 400px;
        align-items: center;
        justify-content: center;
        gap: 295px;
        padding: 40px 43px;
        position: absolute;
        top: 20px;
        left: 20px;
        background-color: #00060a;
    }

    .box .content {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 296px;
        max-width: 1080px;
        position: relative;
        flex: 1;
        flex-grow: 1;
    }

    .box .left {
        width: 195.8px;
        position: relative;
        margin-left: -0.5px;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        justify-content: center;
        gap: 33px;
    }

    .box .branding {
        display: inline-flex;
        align-items: center;
        gap: 2px;
        padding: 1px 10px 1px 0px;
        position: relative;
        flex: 0 0 auto;
    }

    .box .light-mode {
        position: relative;
        width: 32px;
        height: 32px;
    }

    .box .DEEP {
        position: relative;
        width: 151.8px;
        height: 37px;
        overflow: hidden;
    }

    .box .text-wrapper {
        position: absolute;
        width: 155px;
        height: 66px;
        top: 3px;
        left: -2px;
        text-shadow: -5px 6px 4px #1e1e1eb5;
        background: linear-gradient(180deg, rgb(7, 157, 237) 0%, rgb(0, 37.13, 61.89) 100%);
        -webkit-background-clip: text !important;
        background-clip: text;
        -webkit-text-fill-color: transparent;
        text-fill-color: transparent;
        font-family: "Bevan-Regular", Helvetica;
        font-weight: 400;
        color: transparent;
        font-size: 32px;
        letter-spacing: 0;
        line-height: 100px;
        white-space: nowrap;
    }

    .box .copyright {
        position: relative;
        width: 171px;
        height: 16px;
    }

    .box .element-all-rights {
        position: absolute;
        height: 14px;
        top: 0;
        left: 0;
        font-family: "Roboto-Light", Helvetica;
        font-weight: 300;
        color: #eaecf6;
        font-size: 12px;
        letter-spacing: 0;
        line-height: normal;
        white-space: nowrap;
    }

    .box .right {
        position: relative;
        margin-right: -0.5px;
        display: flex;
        flex-direction: column;
        width: 471px;
        align-items: flex-end;
        justify-content: center;
        gap: 20px;
    }

    .box .div {
        color: #eaecf6;
        position: relative;
        width: fit-content;
        margin-top: -1px;
        font-family: "Roboto-Bold", Helvetica;
        font-weight: 700;
        font-size: 22px;
        letter-spacing: 0;
        line-height: normal;
        white-space: nowrap;
    }

    .box .text-wrapper-2 {
        position: relative;
        width: 471px;
        font-family: "Roboto-Regular", Helvetica;
        font-weight: 400;
        color: #eaecf6;
        font-size: 18px;
        text-align: right;
        letter-spacing: 0;
        line-height: normal;
    }

    .box .socials {
        position: relative;
        width: 160px;
        height: 24px;
    }

    .box .social {
        position: absolute;
        width: 13px;
        height: 23px;
        top: 0;
        left: 0;
    }

    .box .social-2 {
        position: absolute;
        width: 22px;
        height: 22px;
        top: 1px;
        left: 36px;
        background-image: url(./img/instagram.svg);
        background-size: 100% 100%;
    }

    .box .img {
        position: absolute;
        width: 31px;
        height: 24px;
        top: 0;
        left: 82px;
    }

    .box .social-3 {
        position: absolute;
        width: 23px;
        height: 22px;
        top: 1px;
        left: 137px;
        background-image: url(./img/linkedin.svg);
        background-size: 100% 100%;
    }

    .box .mode-dark {
        display: flex;
        width: 1048px;
        min-height: 200px;
        max-height: 400px;
        align-items: center;
        justify-content: center;
        gap: 295px;
        padding: 40px 43px;
        position: absolute;
        top: 231px;
        left: 20px;
        background-color: #eaecf6;
    }

    .box .content-2 {
        height: 111px;
        max-width: 1080px;
        position: relative;
        flex: 1;
        flex-grow: 1;
    }

    .box .left-2 {
        width: 196px;
        position: absolute;
        top: 12px;
        left: 0;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        justify-content: center;
        gap: 33px;
    }

    .box .p {
        position: absolute;
        height: 14px;
        top: 0;
        left: 0;
        font-family: "Roboto-Light", Helvetica;
        font-weight: 300;
        color: #00060a;
        font-size: 12px;
        letter-spacing: 0;
        line-height: normal;
        white-space: nowrap;
    }

    .box .right-2 {
        position: absolute;
        top: 0;
        left: 491px;
        display: flex;
        flex-direction: column;
        width: 471px;
        align-items: flex-end;
        justify-content: center;
        gap: 20px;
    }

    .box .text-wrapper-3 {
        color: #00060a;
        position: relative;
        width: fit-content;
        margin-top: -1px;
        font-family: "Roboto-Bold", Helvetica;
        font-weight: 700;
        font-size: 22px;
        letter-spacing: 0;
        line-height: normal;
        white-space: nowrap;
    }

    .box .text-wrapper-4 {
        position: relative;
        width: 471px;
        font-family: "Roboto-Regular", Helvetica;
        font-weight: 400;
        color: #00060a;
        font-size: 18px;
        text-align: right;
        letter-spacing: 0;
        line-height: normal;
    }

    .box .social-4 {
        position: absolute;
        width: 22px;
        height: 22px;
        top: 1px;
        left: 36px;
        background-image: url(./img/instagram-2.svg);
        background-size: 100% 100%;
    }

    .box .social-5 {
        position: absolute;
        width: 23px;
        height: 22px;
        top: 1px;
        left: 137px;
        background-image: url(./img/linkedin-2.svg);
        background-size: 100% 100%;
    }
```

</details>

<details>
<summary>index.html</summary>

```html
    <!DOCTYPE html>
    <html>
        <head>
            <link rel="stylesheet" href="globals.css" />
            <link rel="stylesheet" href="styleguide.css" />
            <link rel="stylesheet" href="style.css" />
        </head>
        <body>
            <div class="box">
                <footer class="footer">
                    <div class="mode-light">
                        <div class="content">
                            <div class="left">
                                <div class="branding">
                                    <img class="light-mode" src="img/size-11.svg" />
                                    <div class="DEEP"><div class="text-wrapper">DEEP</div></div>
                                </div>
                                <div class="copyright"><p class="element-all-rights">© 2023 All Rights Reserved</p></div>
                            </div>
                            <div class="right">
                                <div class="div">Duran Enterprise</div>
                                <div class="text-wrapper-2">Elevating Education, Empowering Innovators</div>
                                <div class="socials">
                                    <img class="social" src="img/social.svg" />
                                    <div class="social-2"></div>
                                    <img class="img" src="img/image.svg" />
                                    <div class="social-3"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mode-dark">
                        <div class="content-2">
                            <div class="left-2">
                                <div class="branding">
                                    <img class="light-mode" src="img/size-11-2.svg" />
                                    <div class="DEEP"><div class="text-wrapper">DEEP</div></div>
                                </div>
                                <div class="copyright"><p class="p">© 2023 All Rights Reserved</p></div>
                            </div>
                            <div class="right-2">
                                <div class="text-wrapper-3">Duran Enterprise</div>
                                <div class="text-wrapper-4">Elevating Education, Empowering Innovators</div>
                                <div class="socials">
                                    <img class="social" src="img/social-2.svg" />
                                    <div class="social-4"></div>
                                    <img class="img" src="img/social-3.svg" />
                                    <div class="social-5"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </body>
    </html>
```
</details>
