### ISSUE TITLE
Create Hero component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#5]
![heroContainer](https://github.com/Duran-Enterprise/deep/assets/128191960/55a22e5d-05da-4f33-b7e0-7a536a224572)

<details>
<summary>styleguide.css</summary>

```css
:root {
    --white: rgba(234, 236, 246, 1);
    --black: rgba(0, 6, 10, 1);
    --accent: rgba(7, 157, 237, 1);
    --dark-contrast: rgba(34, 32, 32, 1);
    --buttonsprimary: rgba(22, 119, 172, 1);
    --buttonssecondary: rgba(196, 233, 253, 1);
    --variable-collection-light-contrast: rgba(220, 223, 240, 1);
}

```
</details>

<details>

<summary>style.css</summary>

```css
.hero-container {
    display: flex;
    flex-wrap: wrap;
    max-width: 1080px;
    height: 549px;
    align-items: center;
    justify-content: center;
    gap: 0px 0px;
    padding: 50px 0px;
    position: relative;
    overflow: hidden;
}

.hero-container .headline-section {
    display: flex;
    flex-direction: column;
    width: 540px;
    height: 517px;
    align-items: flex-start;
    justify-content: center;
    gap: 10px;
    padding: 0px 19px;
    position: relative;
    margin-top: -34px;
    margin-bottom: -34px;
}

.hero-container .flexcontainer {
    display: flex;
    flex-direction: column;
    width: 433px;
    align-items: flex-start;
    gap: 25px;
}

.hero-container .text {
    position: relative;
    align-self: stretch;
    font-family: "Inter-Bold", Helvetica;
    font-weight: 400;
    color: transparent;
    font-size: 60px;
    letter-spacing: 0;
    line-height: 60px;
}

.hero-container .text-wrapper {
    font-weight: 700;
    color: #1677ac;
    line-height: 50px;
}

.hero-container .span {
    font-family: "Inter-Regular", Helvetica;
    color: #202020;
    font-size: 20px;
    line-height: 26.5px;
}

.hero-container .buttons {
    display: inline-flex;
    align-items: center;
    gap: 18px;
    padding: 20px 0px;
    position: relative;
    flex: 0 0 auto;
}

.hero-container .get-started {
    display: flex;
    flex-direction: column;
    width: 199px;
    height: 48px;
    align-items: center;
    justify-content: center;
    gap: 10px;
    padding: 8px 24px;
    position: relative;
    background-color: #079ded;
    border-radius: 15px;
    overflow: hidden;
    all: unset;
    box-sizing: border-box;
}

.hero-container .button {
    color: #ffffff;
    position: relative;
    width: fit-content;
    font-family: "Inter-Regular", Helvetica;
    font-weight: 400;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
    all: unset;
    box-sizing: border-box;
}

.hero-container .learn-more {
    display: flex;
    flex-direction: column;
    width: 199px;
    height: 48px;
    align-items: center;
    justify-content: center;
    gap: 10px;
    padding: 8px 24px;
    position: relative;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    overflow: hidden;
    all: unset;
    box-sizing: border-box;
}

.hero-container .div {
    color: #00060a;
    position: relative;
    width: fit-content;
    font-family: "Inter-Regular", Helvetica;
    font-weight: 400;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
    all: unset;
    box-sizing: border-box;
}

.hero-container .product-section {
    position: relative;
    width: 540px;
    height: 684px;
    margin-top: -117.5px;
    margin-bottom: -117.5px;
}

.hero-container .blue-baby-owl {
    position: absolute;
    width: 512px;
    height: 512px;
    top: 86px;
    left: 14px;
    object-fit: cover;
}

```

</details>

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="styleguide.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="hero-container">
            <div class="headline-section">
                <div class="flexcontainer">
                    <p class="text">
                        <span class="text-wrapper">Discover the Depths of Knowledge<br /></span>
                    </p>
                    <p class="text">
                        <span class="span">Dive into a World of Education, Empowerment, and Programming Excellence.</span>
                    </p>
                </div>
                <div class="buttons">
                    <button class="get-started"><button class="button">Get Started</button></button>
                    <button class="learn-more"><button class="div">Learn More</button></button>
                </div>
            </div>
            <div class="product-section"><img class="blue-baby-owl" src="img/blue-baby-owl-1.png" /></div>
        </div>
    </body>
</html>

```
</details>
