### ISSUE TITLE
Create SimpleCard component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#7]
![image](https://github.com/Duran-Enterprise/deep/assets/128191960/6b30b7ec-c58f-47ea-a6a0-718cc68a3cd7)

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="styleguide.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="box">
            <div class="card">
                <div class="card-wrapper">
                    <div class="div">
                        <img class="building-block" src="img/building-block-svgrepo-com-2.svg" />
                        <div class="text-wrapper">Modularized</div>
                    </div>
                </div>
                <div class="card-wrapper">
                    <div class="card-2">
                        <img class="building" src="img/image.svg" />
                        <div class="text-wrapper">Project-based</div>
                    </div>
                </div>
                <div class="card-wrapper">
                    <div class="card-2">
                        <img class="layer" src="img/image.png" />
                        <div class="text-wrapper">Industry-relevant</div>
                    </div>
                </div>
                <div class="card-wrapper">
                    <div class="card-3">
                        <img class="building" src="img/building-construction-svgrepo-com.svg" />
                        <div class="text-wrapper-2">Project-based</div>
                    </div>
                </div>
                <div class="card-wrapper">
                    <div class="card-3">
                        <img class="layer" src="img/layer-2.png" />
                        <div class="text-wrapper-2">Industry-relevant</div>
                    </div>
                </div>
                <div class="card-wrapper">
                    <div class="card-4">
                        <img class="building-block" src="img/building-block-svgrepo-com.svg" />
                        <div class="text-wrapper-2">Modularized</div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

```
</details>

<details>
<summary>style.css</summary>

```css
.box {
    width: 500px;
    height: 740px;
}

.box .card {
    flex-wrap: wrap;
    width: 500px;
    align-items: flex-start;
    gap: 20px 20px;
    padding: 20px;
    position: fixed;
    top: 0;
    left: 0;
    border-radius: 5px;
    border: 1px dashed;
    border-color: #9747ff;
    display: flex;
    overflow: hidden;
}

.box .card-wrapper {
    display: inline-flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    position: relative;
    flex: 0 0 auto;
}

.box .div {
    flex-direction: column;
    width: 220px;
    height: 220px;
    align-items: center;
    justify-content: flex-end;
    gap: 10px;
    padding: 15px 24px 64px;
    position: relative;
    background-color: #262424;
    border-radius: 11px;
    border: 1px solid;
    border-color: #000000;
    display: flex;
    overflow: hidden;
}

.box .building-block {
    position: relative;
    width: 74.07px;
    height: 80px;
}

.box .text-wrapper {
    color: #eaecf6;
    position: relative;
    width: fit-content;
    font-family: "Inter-SemiBold", Helvetica;
    font-weight: 600;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
}

.box .card-2 {
    flex-direction: column;
    width: 220px;
    height: 220px;
    align-items: center;
    justify-content: flex-end;
    gap: 16px;
    padding: 15px 24px 64px;
    position: relative;
    background-color: #262424;
    border-radius: 11px;
    border: 1px solid;
    border-color: #000000;
    display: flex;
    overflow: hidden;
}

.box .building {
    position: relative;
    width: 60px;
    height: 60px;
}

.box .layer {
    position: relative;
    width: 46.01px;
    height: 56.84px;
}

.box .card-3 {
    flex-direction: column;
    width: 220px;
    height: 220px;
    align-items: center;
    justify-content: flex-end;
    gap: 16px;
    padding: 15px 24px 64px;
    position: relative;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    border: 1px solid;
    border-color: #000000;
    display: flex;
    overflow: hidden;
}

.box .text-wrapper-2 {
    position: relative;
    width: fit-content;
    font-family: "Inter-SemiBold", Helvetica;
    font-weight: 600;
    color: #00060a;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
}

.box .card-4 {
    flex-direction: column;
    width: 220px;
    height: 220px;
    align-items: center;
    justify-content: flex-end;
    gap: 10px;
    padding: 15px 24px 64px;
    position: relative;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    border: 1px solid;
    border-color: #000000;
    display: flex;
    overflow: hidden;
}

```

</details>

<details>
<summary>styleguide.css</summary>

```css
:root {
    --white: rgba(234, 236, 246, 1);
    --black: rgba(0, 6, 10, 1);
    --accent: rgba(7, 157, 237, 1);
    --dark-contrast: rgba(34, 32, 32, 1);
    --buttonsprimary: rgba(22, 119, 172, 1);
    --buttonssecondary: rgba(196, 233, 253, 1);
    --variable-collection-light-contrast: rgba(220, 223, 240, 1);
}

```
</details>
