### ISSUE TITLE
Create SimpleCardWDescription component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#8]
![image](https://github.com/Duran-Enterprise/deep/assets/128191960/5a6345d2-ee61-4a50-ae8c-e1cce0d90071)

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="styleguide.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="modularized">
            <div class="card">
                <div class="div">
                    <img class="building-block" src="img/building-block-svgrepo-com.svg" />
                    <div class="text-wrapper">Modularized</div>
                </div>
            </div>
            <p class="p">Learn in modules for flexibility.</p>
        </div>
    </body>
</html>

```
</details>

<details>
<summary>style.css</summary>

```css
.modularized {
    display: inline-flex;
    flex-direction: column;
    align-items: center;
    gap: 20px;
    position: relative;
}

.modularized .card {
    display: inline-flex;
    flex: 0 0 auto;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    position: relative;
}

.modularized .div {
    display: flex;
    width: 220px;
    height: 220px;
    gap: 10px;
    padding: 15px 24px 64px;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    overflow: hidden;
    border: 1px solid;
    border-color: #000000;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    position: relative;
}

.modularized .building-block {
    position: relative;
    width: 74.07px;
    height: 80px;
}

.modularized .text-wrapper {
    position: relative;
    width: fit-content;
    font-family: "Inter-SemiBold", Helvetica;
    font-weight: 600;
    color: #00060a;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
}

.modularized .p {
    position: relative;
    align-self: stretch;
    font-family: "Inter-Regular", Helvetica;
    font-weight: 400;
    color: #000000;
    font-size: 20px;
    text-align: center;
    letter-spacing: 0;
    line-height: 20px;
}

```

</details>

<details>
<summary>styleguide.css</summary>

```css
:root {
    --white: rgba(234, 236, 246, 1);
    --black: rgba(0, 6, 10, 1);
    --accent: rgba(7, 157, 237, 1);
    --dark-contrast: rgba(34, 32, 32, 1);
    --buttonsprimary: rgba(22, 119, 172, 1);
    --buttonssecondary: rgba(196, 233, 253, 1);
    --variable-collection-light-contrast: rgba(220, 223, 240, 1);
}

```
</details>
