### ISSUE TITLE
Create CourseCards component

### ISSUE THREAD

**Issue by DDuran19** [Duran-Enterprise/deep#9]
![image](https://github.com/Duran-Enterprise/deep/assets/128191960/9d08a6b1-6d82-4197-937e-7138404b5483)

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="globals.css" />
        <link rel="stylesheet" href="styleguide.css" />
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <div class="course-cards">
            <div class="div">
                <div class="card">
                    <div class="card-2">
                        <img class="building-block" src="img/building-block-svgrepo-com.svg" />
                        <div class="text-wrapper">Modularized</div>
                    </div>
                </div>
                <p class="text-wrapper-2">Learn in modules for flexibility.</p>
            </div>
            <div class="div">
                <div class="card">
                    <div class="card-3">
                        <img class="building" src="img/building-construction-svgrepo-com.svg" />
                        <div class="text-wrapper">Project-based</div>
                    </div>
                </div>
                <div class="text-wrapper-2">Hands-on coding with projects.</div>
            </div>
            <div class="div">
                <div class="card">
                    <div class="card-3">
                        <img class="layer" src="img/layer-2.png" />
                        <div class="text-wrapper">Industry-relevant</div>
                    </div>
                </div>
                <div class="text-wrapper-2">Skills for tech careers.</div>
            </div>
        </div>
    </body>
</html>

```
</details>

<details>
<summary>style.css</summary>

```css
.course-cards {
    display: inline-flex;
    align-items: flex-start;
    justify-content: center;
    gap: 29px;
    padding: 36px 0px 0px;
    position: relative;
}

.course-cards .div {
    display: inline-flex;
    flex-direction: column;
    align-items: center;
    gap: 20px;
    position: relative;
    flex: 0 0 auto;
}

.course-cards .card {
    display: inline-flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    position: relative;
    flex: 0 0 auto;
}

.course-cards .card-2 {
    gap: 10px;
    display: flex;
    flex-direction: column;
    width: 220px;
    height: 220px;
    align-items: center;
    justify-content: flex-end;
    padding: 15px 24px 64px;
    position: relative;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    overflow: hidden;
    border: 1px solid;
    border-color: #000000;
}

.course-cards .building-block {
    position: relative;
    width: 74.07px;
    height: 80px;
}

.course-cards .text-wrapper {
    position: relative;
    width: fit-content;
    font-family: "Inter-SemiBold", Helvetica;
    font-weight: 600;
    color: #00060a;
    font-size: 20px;
    letter-spacing: 0;
    line-height: 19.5px;
    white-space: nowrap;
}

.course-cards .text-wrapper-2 {
    position: relative;
    align-self: stretch;
    font-family: "Inter-Regular", Helvetica;
    font-weight: 400;
    color: #000000;
    font-size: 20px;
    text-align: center;
    letter-spacing: 0;
    line-height: 20px;
}

.course-cards .card-3 {
    gap: 16px;
    display: flex;
    flex-direction: column;
    width: 220px;
    height: 220px;
    align-items: center;
    justify-content: flex-end;
    padding: 15px 24px 64px;
    position: relative;
    background-color: var(--variable-collection-light-contrast);
    border-radius: 11px;
    overflow: hidden;
    border: 1px solid;
    border-color: #000000;
}

.course-cards .building {
    position: relative;
    width: 60px;
    height: 60px;
}

.course-cards .layer {
    position: relative;
    width: 46.01px;
    height: 56.84px;
}

```

</details>

<details>
<summary>styleguide.css</summary>

```css
:root {
    --white: rgba(234, 236, 246, 1);
    --black: rgba(0, 6, 10, 1);
    --accent: rgba(7, 157, 237, 1);
    --dark-contrast: rgba(34, 32, 32, 1);
    --buttonsprimary: rgba(22, 119, 172, 1);
    --buttonssecondary: rgba(196, 233, 253, 1);
    --variable-collection-light-contrast: rgba(220, 223, 240, 1);
}

```
</details>
